### ISSUE TITLE
maxChatLength should be 3000 

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1001]
maxChatLength is currently 200; it should be 3000.

~It is currently being applied to private messages but should not be.~

**Comment by Alys** [comment]
Actually, we might decide to apply it to PMs. Discussion in https://github.com/HabitRPG/habitica/issues/10549
I'll update this when a decision is made.

**Comment by Alys** [comment]
We've decided it will apply to PMs. I've updated the top post.

**Comment by Alys** [comment]
Has this been fixed? From what I can see the incorrect value is still in the code (https://github.com/HabitRPG/habitica-android/commit/9e7ae94979cb54f7809b9d6deea349f15b4a4e81#r29708797 )

**Comment by phillipthelen** [comment]
Yes, it was fixed earlier this week. In the release branch the value is correct ( https://github.com/HabitRPG/habitica-android/blob/release/Habitica/src/main/java/com/habitrpg/android/habitica/ui/views/social/ChatBarView.kt#L30 ).
On develop the value is still incorrect, but it's also not used anymore since the value is now set via the remote config. But I'll also change it there, so that it has the correct fallback.
