### ISSUE TITLE
Translations: Russian timestamp translations may be wrong

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1096]
Had a user report that a message said it came in '2 months ago' when it was supposed to be '2 minutes ago'. Is there any way we can check the translations? Even if its just google translate. If everything seems okay, maybe just close issue since the original report didn't follow up with more details.

**Comment by phillipthelen** [comment]
I ran the strings ("1 minute ago" and "x minutes ago") through google translate and it looks like they are indeed translated incorrectly. Most likely because the original string is "Xm ago" and the translator thought that was supposed to be months (although the variable is called `ago_minutes`. I'll mark this issue in transifex
