### ISSUE TITLE
daily and To-Dos filter breaks when app resumes

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-android#1112]
If the app is in the background (not sure how long is necessary to trigger this), the app doesn't show the daily filter options anymore but instead shows the habit weak/strong ones.

**Comment by Alys** [comment]
Also happens for To-Dos:

"On mobile (android), when I click on To-Dos or Dailies and then on the filter at the top, it still shows Weak/Strong rather than Due/Grey, Scheduled/Complete. It only happens some of the time, sometimes it works perfectly." -- Marie   @liongirl15007 (7847ca82-9b0d-460c-9cf7-75f2e32a028f)  and confirmed by me.

**Comment by kweeket** [comment]
This still repros for me. On android, Samsung Galaxy S7.

**Comment by saraolson** [comment]
@kweeket what version are you on?

**Comment by kweeket** [comment]
Version 1.9.1 (2133)

**Comment by saraolson** [comment]
@kweeket is this an issue you can easily reproduce? its been hard for us to track down, making it hard to fix. if you get it frequently, it would be helpful if you could walk us through the steps

**Comment by kweeket** [comment]
I wouldn't say it's easy to reproduce, unfortunately, even though I typically get the bug multiple times a day.  It only happens when returning to the app via my homepage shortcut after it's been running in the background for a while, but it doesn't happen EVERY time.  

It's not purely time based, because yesterday it didn't happen until 8pm (after multiple times of marking stuff off awhile the app continued to run in the background) and today it happened at 10am, the first time I returned to the app after marking stuff off in the morning.

I will continue to try different things to see if I can reliably trigger the bug.

**Comment by saraolson** [comment]
@kweeket thank you for explaining that and please do update us here if you figure out any pattern

**Comment by saraolson** [comment]
from @gnatt123
"For over 6 months, whenever the app is opened after being in the background for more than 5 minutes or so (whenever it opens in such a way that it has a brief white screen while it reopens itself), all the filters are broken for to-dos and dailies. Filter options for dailies show all/weak/strong, instead of all/due/grey, and whatever is selected, everything is shown. App has to be closed and restarted to work normally. Happens 10-20 times per day. Exact same issue on this phone and my previous. Happy to get screen capture to demonstrate if necessary."
