### ISSUE TITLE
Ability to share a Challenge

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1118]
Have a 'Share Challenge' option in the overflow menu accessible through the Challenge details screen that would give users a copied link they can then paste into whatever chat service they'd like to allow friends to view and potentially join a Challenge.

This is a quick way to add the ability to share a Challenge without having to go through the implementation of inviting and notifying. It could also be useful for people who would like to share the Challenge with a larger group without having to individually notify accounts (ie social media)

**Comment by bacowan** [comment]
Hi! I finished up my last issue really quickly (still in PR though), so I'd like take on this issue as well if that's all right. Are we just looking for a menu option that copies the challenge URL to the clipboard?

**Comment by bacowan** [comment]
Also, this issue will probably need a new string in `strings.xml` (for a toast confirming that the URL was copied), meaning translation work. What's the process for that? Just make the PR with English and let translators take it from there?

**Comment by saraolson** [comment]
@bacowan hello there! you're welcome to take this on. and yup, its just an option from an overflow menu that lets someone copy the challenge url link or choose an app they'd like to send the link to using android's default share sheet.

UX would be:
-Tap overflow menu
-Tap 'Share Challenge'
-Android share sheet comes up with the option to 'Copy to Clipboard' and list of various messaging apps (gmail, discord, ect ect. normal share stuff)
-User can select to just copy to clipboard from there, in that case android should handle the toast
-If they choose an app to share it to, share the link text to whichever app they chose and let that app handle it from there

Let me know if you have any questions!

**Comment by bacowan** [comment]
@saraolson Good stuff, I like descriptive instructions. I'll probably have some questions later. Thanks!

**Comment by bacowan** [comment]
Just so that I know I'm on the right track, this is what it looks like with the built in sharing functionality (`ShareActionProvider`):

![image](https://user-images.githubusercontent.com/5496948/57002918-40a16c80-6b99-11e9-96ac-3ae09068fcfb.png)

After clicking "Share":

![image](https://user-images.githubusercontent.com/5496948/57002929-52830f80-6b99-11e9-8301-6ea6ae6a2989.png)

I think it just puts in whatever apps you have installed that you can share to. I think I should be able to put a Clipboard option in there as well.

That what you had in mind?

**Comment by phillipthelen** [comment]
Hey @bacowan 

We were thinking of using the `ACTION_SEND` intent for this, since that will display a sheet with all the available options including an option to copy the text to clipboard. https://developer.android.com/training/sharing/send

**Comment by bacowan** [comment]
Hey @phillipthelen 

Sounds good. Turns out that [the copy action is actually a part of Google Drive App](https://www.androidpolice.com/2012/11/29/tip-drives-latest-update-adds-global-copy-to-clipboard-option-in-the-share-menu/), so the reason it's not appearing in the above screenshot is because the emulator I was using didn't have that installed. The `ShareActionProvider` that I'm using above uses the `ACTION_SEND` intent, so the only difference between using that and starting the share activity with `startActivity()` appears to be UX (though I'm not 100% sure). I switched over to an emulator with the Google Drive App installed for the following screenshots.

Using `ShareActionProvider`:

![third](https://user-images.githubusercontent.com/5496948/57186354-fe876c00-6eb3-11e9-9431-cda69e9e6309.PNG)

Using `startActivity()`:

![second](https://user-images.githubusercontent.com/5496948/57186357-10690f00-6eb4-11e9-92c2-599afdb790bc.PNG)

Thoughts?

**Comment by saraolson** [comment]
@bacowan the bottom sheet one looks good to me! @phillipthelen any suggestions?

**Comment by saraolson** [comment]
@bacowan k looks good!

**Comment by Alys** [comment]
Something that might need to be considered, if it hasn't been already...

If the challenge is hosted in a private Guild or Party, then it's likely that the people it's shared with won't be able to see or join the challenge (they'll effectively see it as a broken link). Should the share option not appear for challenges in private groups? Or should there be a notification to the person sharing it that they should share to only group members (perhaps ideally by posting in group chat about it) and/or they should invite the people they want to share to the to group first?

BTW, I wouldn't recommend that a guild/party invitation be automatically issued as part of the challenge sharing process, as that might not be appropriate for all groups, and would fail in some cases (a full party or a group with a Group Plan if the sharer wasn't the leader).

The person sharing the challlenge might have forgotten that the group is private, so they might not think of these issues themself.

@bacowan These are just ideas that occurred to me, so don't take action on this unless the staff say to. :)

**Comment by saraolson** [comment]
@Alys i think for now let's just let them run into that wall. we already have a private link sharing UX issue so i think this problem can be attempted to be addressed with that one. ie some text on a page when you try to access a private space you don't have access to through a link, then that user can go back and be like 'it says it's private', similar to if you share a link to say a google doc or git hub repo you dont have access to. you get a 404 or some various error that tells you there's some blocker. then the person who linked can decide whether to extend and invite or not.

wouldn't limit sharing/link options in private spaces cause they could very well be tryin to link to someone who is a member.
