### ISSUE TITLE
Mana bar isn't hidden correctly when user hasn't selected a class

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1123]
The profile and main header UI of a lvl 10+ user who hasn't selected a class doesn't hide the mana bar correctly. When comparing the profile on mobile to web, mobile shows the mana bar and web does not.

**Comment by ClouddJR** [comment]
Do you mean the full screen profile view? It seems that it works for me. I am entering the profile screen from Tavern if that matters

**Comment by saraolson** [comment]
Ah whoops, this was originally a report from a user that I just passed on to GH but after testing it myself it seems to only happen when a user is level 10+ but hasn't selected a class. i'll correct the original comment.

**Comment by Alys** [comment]
We have this issue too for the mana bar appearing and other related problems when a user has opted out: https://github.com/HabitRPG/habitica-android/issues/739 ("players who have opted out of the class system can use Warrior skills and see Mana and see Stats Points options")

**Comment by phillipthelen** [comment]
I can't seem to reproduce this? On an account that is opted out of the class system, it correctly hides the mana bar. And getting to the state where the website constantly prompts you to choose a class also does not show a mana bar.

**Comment by saraolson** [comment]
huh yeah i can't either anymore. welp guess i'll close this? if it comes up again, we can reopen.

**Comment by Alys** [comment]
I'm reopening this because it's happening again.

The screenshot and data below are from a player who should not be seeing a mana bar.

You can get to this state by creating a new account and setting the level to 10 using Fix Character Values, and probably through other routes, although the exact methods of getting there aren't important.

The only time a mana bar should appear is if `preferences.disableClasses` is `false` and `flags.classSelected` is `true` (that ensures the player has selected a class and has not opted out of the class system).

```
{
    "_id": "c6d5c4af-d55b-466c-ad7f-5dfa85b92ba7",
    "auth": {
        "local": {
            "username": "alys123"
        }
    },
    "flags": {
        "classSelected": false
    },
    "preferences": {
        "disableClasses": false
    },
    "stats": {
        "lvl": 10,
        "class": "warrior"
    },
}
```

![image](https://user-images.githubusercontent.com/1495809/79038530-5169b780-7c1d-11ea-9f9b-cab48b61fec1.png)
