### ISSUE TITLE
Link to Party Wanted Guild on the 'no party' screen

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1126]
Updating the text above the username button to say:
"Give the username below to a friend or head to the [Party Wanted Guild] to meet potential comrades!"
[should link to the Party Wanted Guild]

Assigning this to Phillip because we'd like to a/b test this change.
Track the cohort's:
-% landing in 'party wanted guild'
-% that end up in parties (either as leader or member)
-retention in general

<img width="362" alt="Screen Shot 2019-04-05 at 3 42 06 PM" src="https://user-images.githubusercontent.com/12453119/55653188-bcd3aa80-57bb-11e9-98a8-893a2ca4824c.png">

**Comment by Alys** [comment]
Just as a suggestion, if it links to the default screen for the guild rather than the chat screen, they'll see the instructions there, which will let them know they can also use the guild for advertising to get new members for their own party if they choose to create one, and it will tell them to not use the Tavern for party posts - definitely something mods and socialites would want them to read! :)

**Comment by saraolson** [comment]
@Alys changed the original comment instructions to link to the details screen rather than straight to chat
