### ISSUE TITLE
can't log in to Habitica website on non-default mobile browser

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1159]
On my Android phone, I have Firefox as my default browser. I needed to log in to the Habitica website using Chrome to test a bug, however the app does not allow me to do that. When I click the login button, it asks me if I want to open with the Habitica app or with my default browser. There's no way to scroll or click to select a different browser. See the screenshot below.

The behaviour I was expecting is either:
1. any app that's capable of displaying a website should be selectable in that screen
2. the website should just immediately open in the browser that I'd already chosen to use.

~I'll leave this as suggestion-discussion for a few days and then mark it as help wanted for the first option if there's no other option preferred.~ _[No longer relevant now that this has been moved to the Android repo.]_

My personal preference is the second option but the first is likely to be more flexible for more people.

![image](https://user-images.githubusercontent.com/1495809/57978924-43390880-7a59-11e9-971e-bb5bc0db03c6.png)

**Comment by phillipthelen** [comment]
Apart from being able to add our own app into this screen, we have no control over what apps are shown here. I don't know why chrome isn't shown here, but I can't think of anything that would be the apps fault. The reason this dialog shows is because you have not yet chosen a default behaviour for habitica.com urls. If you select firefox and choose always, it won't happen anymore. But the way this works, we can't prevent it from showing afaik. (it of course doesn't show if you don't have the app installed)

**Comment by Alys** [comment]
I definitely don't want a default behaviour for habitica.com URLs. I need to open them in the app sometimes and Firefox at other times, and (ideally) Chrome also when necessary for testing. So the problem isn't that the dialog appears (I want it to appear), it's that it doesn't contain a non-default browser.

However from what you're it's sounding like that's not something that can be fixed so I'll close this.

**Comment by paglias** [comment]
Hmm I'm not sure if it's just me but I'm unable to login using Google/fb at all on mobile if I have the app installed. If I select to open all habitica urls in chrome then it keeps redirecting me to the login page
