### ISSUE TITLE
Challenge list item summary should display markdown

### ISSUE THREAD

**Issue by Nikosmonaut** [HabitRPG/habitica-android#1244]
**Describe the bug**
Challenge summary display plain text. And do not interpret markdown nor emojis.

**To Reproduce**
Menu => Challenges => Scroll to find a challenge

**Expected behavior**
I think the summary should display markdown and/or emojis like the title

**Screenshots**
![image](https://user-images.githubusercontent.com/45662151/68281432-ec130880-0077-11ea-8513-851ff497d55f.png)
![image](https://user-images.githubusercontent.com/45662151/68281450-f33a1680-0077-11ea-9925-35688084272a.png)

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - OS: Android 10
 - App Version: 2.3
 - Habitica Username: nikosmonaut

**Comment by phillipthelen** [comment]
I agree it should display emojis, but I'm not sure we want the markdown here? looking at your screenshot, the second guild would load a gif, which would be quite disruptive to have in the guild list. Instead, stripping the markdown and just showing it without formatting might be better?

**Comment by Nikosmonaut** [comment]
I thought it was just forgotten to implement.

Just checked the Markwon doc and I'm not sure it has a strip markdown feature.

**Comment by saraolson** [comment]
After lots of discussion, we've decided that we won't be supporting markdown in summary text to retain the experience of users browsing the Challenge list. Summaries were meant to be a quick snapshot of what the Challenge is about, to help users make a decision whether they want to see more. It's not a place for Challenge owners to try to grab their attention over other Challenges with images or text styles. Since we've reached this conclusion, I'll be closing this.
