### ISSUE TITLE
Linting and permissions

### ISSUE THREAD

**Issue by sguzmanm** [HabitRPG/habitica-android#1248]
**Describe the bug**
I am sorry I didn´t do a pull request of this but I am still analyzing some parts of the code. I just wanna know why you guys have the following two things in the app: 

1. READ_PHONE_STATE permission: This permission gives access to incoming phone calls and user communications, and Habitica in general should not request this type of actions. (Manifest line 8)

2. Why do you have an empty implementation for Crashlytics proxy? Any project for implementing this in future commits?

**Comment by phillipthelen** [comment]
1. I believe that permission was added, so that the app knows if the user has a network connection or not. However it wasn't evaluated in a long time if that permission would still be needed. So it might be possible to remove it.

2. The CrashlyticsProxy has an implementation if it is built as release. See the implementation here: https://github.com/HabitRPG/habitica-android/blob/develop/Habitica/src/release/java/com/habitrpg/android/habitica/proxy/CrashlyticsProxyImpl.java
