### ISSUE TITLE
Setting language to Hebrew creates odd appearance of settings page

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1427]
![_20201126_090549](https://user-images.githubusercontent.com/8144640/100445861-b3d8d080-30a5-11eb-982c-4754e140783f.JPG)

Device: Sony F5321
Android Version: 25
AppVersion: Version 3.1 (2660)
BETA
User ID: 33bb14bd-814d-40cb-98a4-7b76a752761c
Level: 81
Class: rogue
Is in Inn: false
Uses Costume: true
Custom Day Start: 16
Timezone Offset: -60

**Comment by saraolson** [comment]
is the desired fix just that the settings page has a longer line length? im guessing the right side text is becuase hebrew is a rtl language, but we dont have translations in place for settings?

**Comment by Nakonana** [comment]
@saraolson yeah looks like the heading ("Profile" etc.) is defining the line length for its notes.

As for the translations, I just checked and the majority of settings strings is indeed not translated, but there's definitely also a translation bug present as can be seen by the German word "Einstellungen" in the screenshot above but also by the fact that at least for "Logout" there's a Hebrew translation:

![Screenshot_20201130-190701](https://user-images.githubusercontent.com/68129995/100647547-fc131f80-333f-11eb-8808-ebc51883d048.png)

**Comment by saraolson** [comment]
@Nakonana thanks for the clarification!

**Comment by JofielB** [comment]
I was able to reproduce the error and I think that I am starting to know where is the problem. Let me explain the experiment that I made 
The first thing that I noticed is that when you change the language from English to Hebrew some UI elements from the application are mirrored (I still don't know if this is a feature of the app or if it is something that android does for some languages). And I believe that this is the root of the problem because I was using two apps of Habitica, the one from the play store and the other one is from the project and when I changed the languages to Hebrew from the project one the UI from the app of the play store was mirrored to and the error occurred too but the language was in English. 
So I am pretty sure that the problem is because of that flip of the UI that happens when the language is changed

### Normal UI
![Issue 2](https://user-images.githubusercontent.com/32725639/100810646-22939200-33f6-11eb-876a-0330ee34c6fc.jpg)

### Mirrored UI (this happened when you change the languages)
![Issue 3](https://user-images.githubusercontent.com/32725639/100810876-9df54380-33f6-11eb-9d5b-c805b8d32bbd.jpg)

### Error reproduced with the English language because of the mirrored UI
![Issue](https://user-images.githubusercontent.com/32725639/100810954-cd0bb500-33f6-11eb-86b5-234cdce59f2e.jpg)

**Comment by JofielB** [comment]
If it is possible I would like to take this issue to continue with the investigation and start coding.

**Comment by saraolson** [comment]
@JofielB youre welcome to take this on but just to be clear, the app is supposed to be mirrored in languages that are read right to left, like hebrew. so we dont want to prevent the app from mirroring. what we dont want to happen is for the line length to be limited on settings page. the mirroring is fine. 

since our translations are done by volunteers, we dont have full translations for every language. so any gap in translations will still show english. however there does seem to be an issue where words that do have hebrew translation are not shown (as pointed out by nakonana above)

**Comment by JofielB** [comment]
@saraolson Got it, I am gonna start working on it

**Comment by JofielB** [comment]
This pull request fixes the error but for example, the APP SETTINGS title is not mirrored, but that is not an error, that happens because that string doesn't have a translation yet. To test that I use a string with translation in Hebrew and it was mirrored as expected.

- In here the APP SETTINGS title is not mirrored because it doesn't have a translation 

![App settings](https://user-images.githubusercontent.com/32725639/100958314-5a273a80-34d9-11eb-8485-e97148730493.png)

- When we put a translation to the world it will be automatically mirrored

![App settings 2](https://user-images.githubusercontent.com/32725639/100958322-5d222b00-34d9-11eb-917f-8cf7097fb5e6.png)
