### ISSUE TITLE
Dailies not being loaded when the app starts

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1440]
"Periodically, when logging into the application, existing habits and daily tasks are not loaded. Restarting the application helps every other time."

Pulling down to reload doesn't help.

> Device: ZTE ZTE BLADE V0920
> Android Version: 27
> AppVersion: Версия 3.1 (2675)
> User ID: 2bc17195-93c4-4200-99f1-ac419ba65ce9
> Level: 5
> Class: warrior
> Is in Inn: false
> Uses Costume: false
> Custom Day Start: 0
> Timezone Offset: -180

**Comment by undefiened** [comment]
I have been suffering from (probably) this bug, so I started some investigation and so far I have figured out that the bug occurs in "TaskRecyclerViewFragment" because "ownerID" becomes an empty string after the app is "unloaded" from the memory and loaded back.

The bug can easily be reproduced:
1) Setting in Android VM Developer Options -> Apps -> Don't keep activities to true.
2) Open Habitica, everything is fine, all tasks are visible.
3) Press home button so that the application "minimizes" and you see the launcher screen.
4) Press the button to show the list of the currently running apps.
5) Select Habitica.

Then, the list of Dailies/Tasks is empty unless you switch to something else (go to Stats, Achievement, etc.).

At the first "fresh" launch, this Fragment is created as expected from TasksFragment -> loadTasksLists in the "createFragment" method of the anonymous class (sorry if I am messing up terminology, I am no Java/Kotlin developer) and it sets "ownerId" in TaskRecyclerViewFragment. However, after unloading and loading again, that property becomes "" (an empty string). And after that, this empty string is feeded to `taskRepository.getTasks(this.taskType, ownerID)` which properly fails to load any tasks. I suspect that Android recreates the Fragment from some saved state and in that saved state it doesn't remember the value of "userId" (at least this is the impression I have from https://developer.android.com/guide/fragments/saving-state).

I am very far from Android development, it is pretty hard to wrap my head around it all, so I will continue the investigation, but maybe this information can already help by the time I figure out Android development in such details :)

**Comment by phillipthelen** [comment]
@undefiened That is already a huge help! I will make some changes to how the tasks are loaded, so that the fragment doesn't need the userID anymore. That was an older requirement but now we also have the userID in the TaskRepository itself. That should then fix this bug.
