### ISSUE TITLE
Chat posts always show "x month ago" instead of "x months ago"

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1465]
In chat, old messages are displayed as being x days, months or weeks old, but for months, it actually says (for example) "6 month ago" instead of "6 months ago".

Version 3.1.1 (2692).

**Comment by Mike-Antonacci** [comment]
I'd like to take this one. In strings.XML, the string ago_1month is correct (singular) but the string ago_months is incorrect (it is also singular), and it looks like that's what this user is experiencing. 

I also checked the surrounding strings to see if any of the others (such as weeks or days) were affected, and they are not. So that's good.
