### ISSUE TITLE
Notifications don't take you to the thing you're being notified about

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1505]
When I asked previously, I think the answer was that notifications aren't meant to take you to the guild/screen in question, but that was quite a while ago and users seem to feel it *has* worked sometimes? So checking in on that/getting it on the radar since it is somewhat frequently mentioned.

> Device: Google Pixel 3
> Android Version: 30
> AppVersion: Version 3.2 (2832)
> User ID: 99d93494-687e-4ab7-8cc0-48290c3201ec
> Level: 53
> Class: rogue
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: 300

"Hi. 
I think there is a bug where notifications don't navigate to the related message.
Steps to reproduce:
1) Get notification of direct message, @ in party or guild, or party notification
2) Tap notification in Notifications list (android native not in-app)
3) App either crashes or just goes to main screen. Its unclear if one or the other happens because the app is in the background or closed.
I feel like when I first joined the app that notifications mostly worked to navigate as expected.

I really like the app but there does seem to be some polish issues. I am also an app developer so I know how hard linking from notifications can be."

**Comment by saraolson** [comment]
@shanaqui this is something where in the past we didnt have as good of in-app linking but that has since been upgraded. however some things haven't gotten the upgrade. however, from what i understand bringing this up to phillip when i wanted the @ to bring me to the actual group it came from, @'s are a little different and need an update in the server code to send to the right place (the data sent with the @ needs to contain more info for the app to know what to do).

not sure when we might have the resources to be able to update that, but its on the radar. ill assign it to 3.3 and see if we might have time then but that may be overly optimistic.

**Comment by saraolson** [comment]
I don't believe this is actually a crash, i think its just opening to the default screen.

**Comment by shanaqui** [comment]
Confirmed, I'm not sure how it got tagged as a crash -- I must've typed into the wrong blank I had open!

**Comment by saraolson** [comment]
@shanaqui oh i added the tag after initially reading the users report then after thinkin it through a lil bit decided it prolly wasn't crashing like they listed in their message
