### ISSUE TITLE
Large amount of text in note makes everything disappear

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1506]
![Screenshot_20210301-235315_Habitica(2)](https://user-images.githubusercontent.com/8144640/109981376-c2640300-7cf8-11eb-8f94-05675fad921e.jpg)

Device: samsung Galaxy S7
Android Version: 26
AppVersion: Versione 3.2 (2832)
User ID: 7a62577e-b233-40a3-bcd5-90f403093b97
Level: 16
Class: healer
Is in Inn: false
Uses Costume: true
Custom Day Start: 7
Timezone Offset: -60

![Screenshot_20210302-162938_Samsung Internet](https://user-images.githubusercontent.com/8144640/109981470-da3b8700-7cf8-11eb-9666-534851f994c2.jpg)

^ shows the amount of text they entered.

I can't reproduce this.

**Comment by shanaqui** [comment]
Still troubleshooting this with user, will close if it turns out to be nothing, but this will help me keep track of the thread.

**Comment by shanaqui** [comment]
They've confirmed it always happens with a long note, and is fixed if they delete the note.

**Comment by saraolson** [comment]
to be honest, the notes field were never made to support that much text so this isnt very high priority. will add help wanted to it in case there is an easy fix but otherwise it may just be something where we say 'put less text in your notes' not sure where the breakdown happens but 5k characters is a lot of text.

while we could add a limit, that introduces a bunch of other loose ends to tie up (like web would need to support, then we gotta do something about ppl over the limit, introduce errors ect) so im tempted to just leave this broken or let a contributor work on a fix.

**Comment by saraolson** [comment]
tested, and this doesnt seem to be happening anymore
