### ISSUE TITLE
Gem balance not shown on gift from balance screen, and balance not updating properly after sending Gems

### ISSUE THREAD

**Issue by shanaqui** [HabitRPG/habitica-android#1557]
I haven't reproduced this myself yet, because I don't want to do it with my main accounts. Here's the user report (which also has suggestions for other ways to make things clearer, but I'm making this bug report for the issue where their gem balance did not update):

> Device: samsung Galaxy S7 Edge
> Android Version: 26
> AppVersion: Version 3.2.3 (2934)
> User ID: 7ca1748c-50a8-4c7e-abab-79ba726a9a4c
> Level: 64
> Class: healer
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 0
> Timezone Offset: -60
> Details:
> 
>  I had a bunch of gems from subscription so I thought it would be nice to gift a few to each guild member.
> I did so from Party > select user > Gift Gems > from balance.
> However after the first few it seemed to be taking a while to load or crashing, as after stating amount and clicking gift - the pop up wasn't appearing.
> My gem balance wasnt going down.
> So when the message didnt appear I would exit ans close the app, go back in and try again.
> Then near the end it started giving me a message saying i would have to gift within 1 of my gem balance - but my balance was showing as 30+ gems.
> So I thought it had glitched, and I didnt want all my guildies except 1 to wake up to gems.
> So I bought more gems and gifted.
> 
> So this morning the receipt of each gem gift is on the chat logs and there are loads of duplicates.
> 
> I don't want you to undo the gifting - that my bad for not being more cautious.
> 
> But on the gifting screen, can you have the balance show, and have the UI reload and update that value each time the submit button is pressed. Also maybe change the colour or text of the button/page to give confirmation rather than the usual pop ups.
> 
> I love the pop ups everywhere else, just thinking as a design destinction for the payment process.

**Comment by saraolson** [comment]
1. we should def show the current balance on the gem gifting screen, its in the designs just didnt get implemented. 
2. should def update gem count without a manual refresh, i tested and we do not do this right now
3. not sure what they mean by change the color of the text rather than pop ups. gifting gems from balance is a little unique in that its technically not a payment process, but other processes go through google, and then we confirm. maybe they are asking for a toast confirmation instead of a modal..?
