### ISSUE TITLE
Quest does not automatically start after all party members accept

### ISSUE THREAD

**Issue by CuriousMagpie** [HabitRPG/habitica-android#1675]
**Describe the bug**
All party members accepted a quest, but it did not automatically start.

**Expected behavior**
When all party members accept a quest, it should begin.

**Screenshots**
![Screenshot_20211116-090958_Habitica](https://user-images.githubusercontent.com/78037386/142280119-0279f1f0-6e1b-40e9-967f-86fe504918e6.jpg)

**Smartphone (please complete the following information):**
 - Device: samsung SM-G935U
 - OS: Android 26
 - App Version: Version 3.4.1.1 (3090)
 - Habitica UUID: 45726305-60ec-432c-97ef-28d7c9efebd7

**Comment by Alys** [comment]
This is an example of an API bug / non-yet-implemented feature, in which when a party leader removes party members after quest invitations have been sent, the removed players remain in the quest invitation list (with the default `null` entry), and so the API's quest code doesn't realise that it's okay to start the quest. It's reported at https://github.com/HabitRPG/habitica/issues/11566.  (It can't be fixed with a change to the mobile app since it's an API bug.)

The workaround is for the party leader or quest owner to force-start the quest by clicking the "begin" button where the quest is show in the party screen, but not all party leaders / quest owners know they need to do that. For this specific case, the quest still hasn't started so the person who reported it may need to pass on a message to the party leader / quest owner to force-start the quest.

**Comment by CuriousMagpie** [comment]
@Alys, thanks for this information! I'm still learning my way around what are known and unknown bugs and I didn't see anything about this one so I really appreciate you digging up the link for me.
