### ISSUE TITLE
reminders not scheduling consistently 

### ISSUE THREAD

**Issue by rilygreat** [HabitRPG/habitica-android#1768]
> Device: samsung SM-G960U
> Android Version: 29
> AppVersion: Version 3.5.2 (3310)
> User ID: 3fe02929-c1cb-45b6-84c8-07b60a1d5cc6
> Level: 46
> Class: wizard
> Is in Inn: false
> Uses Costume: true
> Custom Day Start: 2
> Timezone Offset: 240
> Details:
> 
> I have a reminder set on one of my daily tasks that is part of my morning routine. If I have not visited the app before the time I set I do not get a push notification for the task.

**Comment by jcgoble3** [comment]
I'm experiencing the same problem. I have a reminder to brush my teeth in the morning that is supposed to fire at 5:00 AM (an hour before my alarm clock on a typical weekday, so that it's there when I check my phone first thing in the morning), but it does not go off. I have also noticed that the alarm indicator for my 3:00 PM notification (for a different daily) does not appear on the lock screen until after Cron. On one occasion, I did not Cron until later in the afternoon, and thus did not get the 3:00 PM notification either. So it seems to be linked to Cron.

My bug report information:
Device: Google Pixel 6 Pro
Android Version: 32
AppVersion: Version 3.5.2.1 (3318)
User ID: 137c846e-2460-4606-97de-72bc28076773
Level: 9
Class: warrior
Is in Inn: false
Uses Costume: false
Custom Day Start: 4
Timezone Offset: 240

**Comment by jcgoble3** [comment]
It might also be worth mentioning that I use Habitica both via the Android app and via Firefox on my laptop, bouncing between the two depending on which is more convenient in the moment. Frequently, I create tasks via the laptop, then open the app on my phone to add reminders. I have not tested what happens if I Cron via the laptop first before opening the app, as I generally open the Android app first anyway in the morning before I turn my computer on.

**Comment by CuriousMagpie** [comment]
Another user report:

Device: Xiaomi Mi 9T
Android Version: 29
AppVersion: Version 3.5.2.1 (3318)
User ID: 81685960-41bf-4cb8-b714-8c73b5d941c0
Level: 48
Class: wizard
Is in Inn: false
Uses Costume: false
Custom Day Start: 3
Timezone Offset: 360
Details:

(first email from user)
> Hi I have a problem with Record Yesterday's Activity.
I am using habitica with every daily has a notification.
The notifications don't work until I start the app and check the record yesterday's activity.
So I miss the notifications.

(second email from user)
>What I like is that I don't have to open the app for the start of the remainder.
I have to start the app in the morning, sometimes I forget and if that happens, the remainders dont push up, and I will prefer that habitica works as an alarm that doesn't fail.
Is there a way to completely reset the app, and to have an autostart?
I tried the google script to avoid the record yesterday activity, but I always have to start the app.

**Comment by saraolson** [comment]
seems like reminders aren't scheduling for multiple days in advanced anymore..? i did miss my 10:15am reminder, and i had been using the app yesterday

**Comment by jcgoble3** [comment]
Additional information: I was sick over the weekend and spent Saturday and Sunday resting in the Inn. While doing so, my 5am reminder fired just fine. It only fails to fire when I'm *not* resting in the Inn.

**Comment by rilygreat** [comment]
Device Type: Google Pixel 4a
OS: Android 13
App Version: 4.3.3
UUID: 9642c661-d735-4ba2-9ac8-ca07b420a101

A new question from @DrunkunFist
> Hello, The notification (i.e., reminders) functionality is not working properly on Habitica Android. A vast majority of the time I either don't receive the reminders/notifications on the intended date and time or if I do receive them they are delayed. 

i asked them if they could try all the usual fixes (make sure notifs are turned on for the app, check their battery preferences, and delete then remake the task). they followed up with:
>I did a quick test and found the following -
> 
> 1. Tried notifications on 2 different Android devices - did not work (tried all the above suggestions) - I'm not sure if this has anything to do with the recent Android update that dealt with notifications.
> 2. Tried notifications on iOS device - worked flawlessly. 
> 
> some context - the reminders set under 'to dos' aren't working however the reminders set under 'dailies' are working. It's just the 'to do' section. 

i tested this by adding a to-do reminder that was due today and didn't receive that at all. also tried deleting and remaking, still didn't get anything.

**Comment by Hafizzle** [comment]
@rilygreat I'd be happy to look into why to-do reminders aren't working! I'm not sure if you want to reopen this or create another issue referencing to-do reminders not working specifically
