### ISSUE TITLE
Improve tap area on liking messages

### ISSUE THREAD

**Issue by saraolson** [HabitRPG/habitica-android#1861]
Sometimes it can be difficult to tap the right area to like a message, we should take a look at that tap area and see if we can make it easier to tap.

**Comment by LadyAudrey** [comment]
I am interested in contributing as a first-timer! I'd like to see if I can fix this.
I looked around in the code, I think the adjustment would need to be made in [this](https://github.com/HabitRPG/habitica-android/blob/main/Habitica/res/layout/chat_item.xmll) file. Is that accurate?

**Comment by Hafizzle** [comment]
Hi @LadyAudrey - Yup that is correct!

Ideally we'd like to keep the "size" of the view but make the tap area bigger (So if a player were to press slightly outside the Like, it would still Like/Dislike the message). 

If you have any other questions please feel free to ask!

**Comment by LadyAudrey** [comment]
Hi! Took me a bit to re-orient post bootcamp, but I am downloading this now. Excited!

**Comment by saraolson** [comment]
@LadyAudrey marked this issue for you! good luck 🎊

**Comment by jsoberg** [comment]
Hey all! I added a PR to make the entire like container clickable (currently, it's just the + text itself): https://github.com/HabitRPG/habitica-android/pull/2052. Just wanted to note that Google recommends a tap target size of at least 48dp width/height for a11y ([link](https://support.google.com/accessibility/android/answer/7101858?hl=en)), so lmk if you wanted me to adjust this view to be a bit larger and fit that spec.

While investigating this I found some general issues with liking messages that I notated in https://github.com/HabitRPG/habitica-android/issues/2051. I left some notes there and will come back to investigate more when I have some more time, but I separated those issues out into their own ticket since it isn't being caused by the tap target being too small.
