### ISSUE TITLE
Push to F-Droid?

### ISSUE THREAD

**Issue by negue** [HabitRPG/habitica-android#194]
If we decide to push to F-Droid we couldn't use In-App-Purchases (since it needs the Google PlayServices). Maybe even more, but for now it should be only this feature.

Also we'd have to create a different version which doesn't uses the google libraries (don't know if we need to remove or just not use them at all)

**Comment by pinae** [comment]
I have a Android phone without google account and without play services. The app seems to work fine. I guess it would be sufficient to check for the play services if somebody tries to use the in-app-purchases and show an error if they are not installed. F-Droid should accept the app with this behaviour because it does not really depend on the play services.

Having the app in F-Droid would be very helpful for people like me. Installing the app would be much easier and I would get update notifications.

**Comment by h-2** [comment]
> I have a Android phone without google account and without play services. The app seems to work fine. I guess it would be sufficient to check for the play services if somebody tries to use the in-app-purchases and show an error if they are not installed. F-Droid should accept the app with this behaviour because it does not really depend on the play services.

The app also needs to **build** fine without the libraries in place. Is this the case? Then it should be very easy to port I think. Unfortunately there is no IAP or donation system in place inside F-Droid, yet. But the purchases are not essential for the mechanics, right? So people can still just use the web-app once in a while, if they want to buy something.

**Comment by i-need-to-tell-you-something** [comment]
Is there a way to get it as an apk file for Googleless Androids right now? Even though if some features are missing and app might break.
@pinae How did you build it?

**Comment by Alys** [comment]
@i-need-to-tell-you-something : apk files are at https://github.com/HabitRPG/habitica-android/releases

**Comment by pinae** [comment]
I downloaded the APK like Alys pointed out. But I have no automatic updates this way.

Can I help to bring Habitica to F-Droid? Maybe do some test builds?

**Comment by vIiRuS** [comment]
There haven't been any changes made yet to make habitica more compatible with F-Droid, so there aren't any builds there  to test. I haven't looked into it that much yet, but it seems like we would have to find a solution for the IAPs and also have a build server that builds the releases for fdroid? Not sure how that should then work best.
If a contributor works on this, it would be appreciated, since we probably won't have the resources to work on this for a while.

**Comment by h-2** [comment]
> we would have to find a solution for the IAPs

I temporary solution would be to just deactivate them and show a message that people need to go to the web-site to buy diamonds. I understand it would be better for you, if people could buy diamonds immediately, but I think it is still better than not offering Habitica to F-Droid users at all. And tbh, you don't buy diamonds everyday anyway!

> and also have a build server that builds the releases for fdroid?

F-Droid builds and signs the packages themselves by default¹. You only need to provide a build-flag that enables building Habitica without the proprietary components, then F-Droid will take care of the rest.

_¹ Note that if your builds are reproducible you can also decide to build and sign the packages yourself and F-Droid will only verify that it is identical with the one they build and then still publish your package with your signature._

**Comment by DistantParadox** [comment]
Is there still any chance of Habitica getting into the F-Droid store or has this thread been necro'd?  I sure hope the former to be the case.

**Comment by Alys** [comment]
@DistantParadox As @vIiRuS says above, we'd like a contributor to work on this, so currently, the chance of it being done depends on whether anyone wants to volunteer to do it. Until it's done, you can use the apk files from my link above.

**Comment by mandyzhou** [comment]
Since it'll take a bit of work to get the app into the F-Droid store, in the meantime, would it be possible to update the [Releases](https://github.com/HabitRPG/habitica-android/releases) page so that people who don't want to use the Google Play Store can download the app from there?

**Comment by 1810755jiawei** [comment]
hel

**Comment by Clonewayx** [comment]
https://gitlab.com/fdroid/rfp/issues/61
>Links against proprietary libraries, uses untrusted repositories.

**Comment by jcgruenhage** [comment]
I have taken a look into the build.gradle file, to check what needs to be changed for this:
This list is based on a quick online search per dependency, and not an in depth check.

This list is also not complete yet, I will continue to go through the file and add the missing dependencies here.

## Dependencies:

### Plugins:

| Plugin | FLOSS | Builds without |
| --- | --- | --- |
| com.android.application | true | haven't tried |
| com.android.databinding | true | haven't tried |
| io.fabric | false | yes |
| com.neenbedankt.android-apt | true | haven't tried |
| com.noveogroup.android.check | true | haven't tried |

### Buildscript Dependencies

| Classpath | FLOSS | Builds without |
| --- | --- | --- |
| io.fabric.tools:gradle | false | yes |
| me.tatarka:gradle-retrolambda | true | haven't tried |
| com.getkeepsafe.dexcount:dexcount-gradle-plugin | true | haven't tried |
| com.neenbedankt.gradle.plugins:android-apt | true |  haven't tried |
| com.puppycrawl.tools:checkstyle | true |  haven't tried |
| net.sourceforge.pmd:pmd-java | true | haven't tried |

### Repositories

| Repository | Trusted by F-Droid | Builds without |
| --- | --- | --- |
| mavenLocal() | probably not | yes |
| mavenCentral() | probably | yes |
| https://oss.sonatype.org/content/repositories/snapshots | maybe | yes |
| https://maven.fabric.io/public | no | no |
| http://dl.bintray.com/florent37/maven | maybe | yes |
| https://s3.amazonaws.com/repo.commonsware.com | maybe | no |
| https://jitpack.io | probably not, since it supports private repositories | no |

**Comment by jcgruenhage** [comment]
@vIiRuS @Alys Is there anything specific, that I should not remove from the gradle file? I am not sure what the gradle plugin and classpath dependency on fabric.io is needed for, for example, since the app builds fine without that.

**Comment by vIiRuS** [comment]
How are you building the project? Because at least release builds (which is probably what people would want to use if they build it for themselves) should require fabric. I believe for debug builds it uses a different Application class, that does not use fabric.
I'm pretty sure that all of the dependencies in the gradle file are used and thus required. 

count.ly doesn't seem to have crash reporting, which is the part of fabric that we mainly use.

**Comment by jcgruenhage** [comment]
Oh, right, I have been building debug builds..

BUT: Count.ly does have crash reporting ^^

**Comment by 1810755jiawei** [comment]
发自我的 iPhone

**Comment by jcgruenhage** [comment]
I have to look a lot more into this than I thought, since the release builds aren't as "easy" to build as the debug builds. Replacing some closed source libraries with open source counterparts should help with that, but I wonder if that is even desired by Habitica :D

**Comment by h-2** [comment]
Any news on this? I am unfamiliar with how Java works, but why would a release build include more stuff than a debug build? Don't you use the debug build to debug behaviour that your users would encounter? :question:

**Comment by jcgruenhage** [comment]
The release build contains analytics, crash reporting and in-app purchase stuff that is not needed in the debug builds.

**Comment by vIiRuS** [comment]
The release builds contain p.e. amplitude which we use for analytics and fabric, which we use for crash logging. These things are not used in debug builds, since they would either send unnecesary events or make the setup process harder for users wanting to contribute.

**Comment by jcgruenhage** [comment]
Switching to an open system for the crash reports is out of question right now, correct? Countly does crash reporting and analytics too after all.

**Comment by vIiRuS** [comment]
Countly does not allow commercial ise of their free tier though. So we could not use that and for the enterprise edition their pricing is only available after contacting them. So it does not really sound like an alternative.

**Comment by jcgruenhage** [comment]
Their server is released under the AGPL, and their SDKs under MIT, so you're free to host that server yourself and use it without any limitations. Doing so would somewhat protect your users (no additional third party gets data, like fabric does now) too. But that said, if county doesn't fit your needs, so be it.

**Comment by jcgruenhage** [comment]
Just to follow up on that "doesn't allow" thing: It's right, on their website they state that commercial use is only available with their enterprise tier, but the license included with their server grants you usage rights anyway, so you have legal permission to use it for free. They have added some stuff to the license that is not included in the AGPLv3 normally, but only that you need to keep the branding stuff, when distributing modified versions.

**Comment by vIiRuS** [comment]
We talked this through again and we currently do not have the resources to switch to a different, self hosted, crash report / analytics tool.

If I understood it correctly, in order to be allowed on F-Droid, the project could have non-FLOSS dependencies, as long as those are not used for the target that is compiled and pushed to F-Droid. Correct? In that case, if you (or someones else) creates a product flavor for fdroid, that does not use the non-FLOSS dependencies. This should be doable by wrapping the Classes that are used in a wrapper, that has the correct functionality for the regular flavours, but is a dummy for the F-Droid flavor. (similar to how the crashlyticsproxy already works).

**Comment by h-2** [comment]
> If I understood it correctly, in order to be allowed on F-Droid, the project could have non-FLOSS dependencies, as long as those are not used for the target that is compiled and pushed to F-Droid. 

Yes, as long as the proprietary libraries are not required to build the Flavour, it is completely ok.

I would really love to see this, as well. Unfortunately my engineering expertise is totally not in Java and Android.

**Comment by jcgruenhage** [comment]
@vIiRuS thanks for your answer.

For this to work in F-Droid, building the app must be possible without any binaries, which don't have the sources available. That means, not only must the app in the end not contain any proprietary code, but there must be no proprietary dependencies in the build script either.

I currently do not have the time to look into creating a flavor for F-Droid, mostly because I have no idea how that works, and reading up on that and after that working on that stuff doesn't fit into my schedule atm.

**Comment by igoralmeida** [comment]
Just to add some more information: note that several apps in f-droid have their gradle files changed with e.g. sed scripts just before the build starts in order to remove the proprietary dependencies. Meaning, as long as the proprietary bits are not too intertwined with the main application, there is hope.

**Comment by Clonewayx** [comment]
https://gitlab.com/fdroid/rfp/issues/61#note_24944808

**Comment by h-2** [comment]
Why was this close? I know the requirements of F-Droid, but I don't see why a version of Habitica without micro-payments and crash-analytics wouldn't work. Or did I miss something?

Waiting for this since such a long time now...

**Comment by hex-m** [comment]
@phillipthelen could you please explain what closing the issue means? you personally will not work on this one? community contributions related to this would not be merged? Thank you!

If you are interested there is also an issue on the [f-droid tracker](https://gitlab.com/fdroid/rfp/issues/61).

**Comment by phillipthelen** [comment]
We will not work on this. If a community member can make a PR that gets acepted to f-droid I have nothing against merging hat in. However, the issue you are referring to was closed by the fdroid team and it doesn’t sound like they think the app can be made compatible with their guidelines, so I closed the issue.

**Comment by dreua** [comment]
I'd like to fund this issue, initial offer is 300 EUR.

**Comment by asandikci** [comment]
Still no progress in 2024 ?

**Comment by asandikci** [comment]
Maybe @IzzySoft could help/guide. Or at least could we get this app on IzzyOnDroid repo?

**Comment by IzzySoft** [comment]
Afraid not:

```
Offending libs:
---------------
* BillingClient (/com/android/billingclient): NonFreeComp,NonFreeNet
* Crashlytics (/com/crashlytics): NonFreeComp,Tracking
* Google Ads (/com/google/ads): Ads,NonFreeComp
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Cloud Messaging (/com/google/android/gms/cloudmessaging): NonFreeComp,NonFreeNet
* Fido (GMS) (/com/google/android/gms/fido): NonFreeComp
* Play Services Places Placereport (/com/google/android/gms/places_placereport): NonFreeComp,NonFreeNet
* Android Wear APIs (/com/google/android/gms/wearable): NonFreeComp
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet
```

With 11 proprietary components it's unfortunately no longer "really FOSS" and thus cannot be included with either F-Droid.org or IzzyOnDroid, sorry.

**Comment by uncharted-user** [comment]
It's really disappointing as there is no Fdroid version available. :(

**Comment by luanmdlima** [comment]
I guess there isn't enough community pressure for them to care about an f-droid version
