### ISSUE TITLE
Better Flagging Warning Needed

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-android#355]
Currently, the warning for flagging on the Android app doesn't tell you much about what flagging is. It should instead match the more comprehensive warning from the website. (We've been getting a lot of mistaken flags recently, and we suspect that this is why.)

**Comment by Alys** [comment]
In an email, Lemoness suggested renaming it from "Flag" to "Report" (and also ensuring that the translations are changed appropriately).

Maybe it could even be "Report Violation" or "Report Violation of Community Guidelines"? How much can the current "Flag" button be expanded?

It might help too if the triangle icon was changed to red so that it was more clearly a warning/bad icon.

**Comment by saraolson** [comment]
I'm gonna attach this to chat redo to make sure we have this covered when we do that.

**Comment by saraolson** [comment]
made a design for this to incorporate more of the web design into the mobile form while still keeping it comfortable on the smaller screen size.

[Report bottom sheet](https://zpl.io/aX3KMmj)
[Report expanded](https://zpl.io/awJyYg7)

<img width="426" alt="Screen Shot 2019-04-10 at 11 52 11 AM" src="https://user-images.githubusercontent.com/12453119/55895006-4d7a0400-5b89-11e9-932f-3195135e8f2e.png">
