### ISSUE TITLE
Refresh/sync button should appear on more screens

### ISSUE THREAD

**Issue by mandyzhou** [HabitRPG/habitica-android#521]
It would be great if the refresh/sync button were on more screens. For example, after I feed my pets, the food that was used doesn't disappear from my inventory until I manually sync, but that requires going to certain screens (e.g., one of the Tasks or Rewards screens) to access the button.

**Comment by saraolson** [comment]
Would rather add pull to refresh to more screens than a sync button to every screen in the app

**Comment by saraolson** [comment]
There are also certain things that we should just auto sync, like food should auto disappear rather than waiting for a pull to refresh. Ideally, manually syncing would only be required rarely when something seems wrong.
List of screens where pull to refresh could be nice to have:
-Market
-Stable
-Items
-Stats

**Comment by saraolson** [comment]
We're going to close this issue, but not because we don't want it. It's just too broad. It would be better to have specific issues for the behavior we want on each section of the app. We can create those as we come across them.
