### ISSUE TITLE
Losing hatched pets when shifting from market to stable in app.

### ISSUE THREAD

**Issue by dbrdbd** [HabitRPG/habitica-android#534]
Not really sure when or how this happens - seems to happen rarely, but it's happened a few times. Essentially, I'll "hatch" a pet and then when I go to look at it, that pet, potion, and egg no longer exist.

**Comment by saraolson** [comment]
I tested this and think this might be caused by the app not force refreshing after hatching a pet? Combined with no way to actually refresh from the stable screen, it can appear the pet isn't there. When I went to the task screen and forced a refresh, the pet i hatched displayed in stable.

(i didn't do anything from market, just items and stable)
