### ISSUE TITLE
moderators and staff cannot delete other players' chat posts (Tavern, guilds, party)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#556]
Staff and moderators should be able to delete the posts of any player. The API allows it, so this could be done by just enabling the "delete" option on all messages if the user has `contributor.admin` set to `true`

The delete option should have a confirmation step, to prevent mods accidentally deleting a message if their finger slips. Of course, that confirmation step would be fine for displaying to normal players too, when they delete their own messages.

This isn't urgent since we can flag messages to hide them, but sometimes it's useful to delete messages as well (e.g., if it's so vile we don't want to keep seeing it; fortunately very rare).

**Comment by AlbRoehm** [comment]
Hey Alys, i changed the menu and added a confirmation dialog, but i cannot test whether it is working or not. I guess it should work, because if i try to delete post of my real account with my test account i get a message that i am not allowed to do so. I will upload my changes as a PR for this ticket and maybe some you guys can test it, because i dont wanna setup a complete server and so on ...

**Comment by Alys** [comment]
This problem has returned - moderators are no longer able to delete other player's posts.
Version 1.5 (1979)

**Comment by Alys** [comment]
Also in Version 1.5 (1980).

The delete option doesn't appear for my own posts either when logged in as a mod (I haven't tried with a non-mod account).

**Comment by Alys** [comment]
Fixed in Version 1.4.5 (1983) so I'm closing this. Thanks Phillip!
