### ISSUE TITLE
Installation should test that "Developer option, Do not keep activities" is unchecked

### ISSUE THREAD

**Issue by DrStrangepork** [HabitRPG/habitica-android#605]
I stumbled onto this while troubleshooting a different app, but I found that when this option is checked, no New Habit/Daily/Todo/Reward actions get saved. When you hit on the '+' icon, it goes to the appropriate screen, but when you hit Save, nothing gets saved. Not sure if the content is not retained or if the API call fails, but unchecking "Developer option, Do not keep activities" - which is to say, changing the setting back to normal - returned the normal, functional behavior to the app.

**Comment by AlgoRyan** [comment]
Preventing the user from checking this developer won't solve the root problem, which is that some code somewhere isn't dealing correctly with the possibility of the UI being killed. 

The ideal solution to the issues you mentioned is to fully test the app with DKA enabled and fix states where information is lost. Otherwise users will intermittently experience loss of state and weird behaviours, like the ones you discussed.

**Comment by vIiRuS** [comment]
Yes, Currently the Form activity expects the MainActivity to be there. We will fix this in a planned refactoring.

**Comment by vIiRuS** [comment]
This is no longer necessary, since it now also works with that setting active.
