### ISSUE TITLE
FAQ "How do I set up my tasks?" missing symbols

### ISSUE THREAD

**Issue by goldfndr** [HabitRPG/habitica-android#611]
In the app, the Help & FAQ item "How do I set up my tasks?" is missing the + and - symbols. Given HabitRPG/habitrpg#5773's HabitRPG/habitrpg@869651f5a2dfc824ae65b2a6bf55f0940a6769bf (FAQbodySetUpTasks-1), it's clear that the FAQ is using glyphicons. These could perhaps be substituted on-the-fly. Version 0.0.33.2.

**Comment by vlad-vassilovski** [comment]
Yep, it's a bug and it may be a backend issue.

Here, it can be seen that there are separate FAQ answer strings for Android which don't include glyphicons and so may be displayed better within the app: https://github.com/HabitRPG/habitrpg/blob/81b7eeeb711cc68ccc22705513142d82d2f7cdea/website/common/locales/en/faq.json

And here's the Android code that tries to pull out the Android-specific strings and falls back to the web app's answer strings with glyphicons if no Android strings are available: https://github.com/HabitRPG/habitrpg-android/blob/0ed79c8b535ab34ea05dfc50b74a1f708f857869/Habitica/src/main/java/com/magicmicky/habitrpgwrapper/lib/utils/FAQArticleListDeserilializer.java

But the web app's strings are always used because the FAQ JSON only seems to contain the web and iOS strings for each question, not the Android ones:

```
"faq": {
  "questions": [

    ...
  
    {
      "question": "How do I set up my tasks?",
      "ios": "Good Habits (the ones with a +) are ..."
      "web": "Good Habits (the ones with a <span class='glyphicon glyphicon-plus'><\/span>) are ..."
    },

    ...

```

I'm not familiar with the backend, but perhaps this is at least one file that needs updating to handle Android in addition to web and iOS: 
https://github.com/HabitRPG/habitrpg/blob/81b7eeeb711cc68ccc22705513142d82d2f7cdea/website/common/script/content/faq.js
