### ISSUE TITLE
Tags with tasks are not in the same order as online or in tag filter

### ISSUE THREAD

**Issue by DrStrangepork** [HabitRPG/habitica-android#615]
When creating/editing a task, the order of tags is by tag creation date. The "Filter by Tag" side menu is in the same order as the customized order of tags on the website.

**Comment by andrewlord1990** [comment]
Regardless of the order I make the tags on the website, the tags in the "Filter by Tag" side menu are in creation date order just like the new task page. The queries to get the tags for both of these locations in the app are also the same. I'm not sure if this logic has changed at some point since you observed this.

**Comment by DrStrangepork** [comment]
This may have gotten fixed with the latest update, or any install/update refreshes the order.

**Comment by LordVladneutral** [comment]
What I observed about this :
The list of tags in the task creation menu may vary in the same opening of the app, from one task to an other. It only varied between two positions, the order in which the tags are displayed on the site, and the order in which they are displayed on the site, minus sorting done after loggin into the app.
The sidebar always showed the latter.
Logging in and out solved the problem.
