### ISSUE TITLE
Reorder reward list

### ISSUE THREAD

**Issue by kai11** [HabitRPG/habitica-android#627]
I can reorder Habits, Dailies and To Did, but Rewards stay in the same order - like I entered them, so I cannot put one reward on top without swapping it with something else.
Please fix

**Comment by AlbRoehm** [comment]
Tryed to implement it on my phone and just had to change a few things. As long as you drop try to move them between equipment rewards everything is fine. But if you mix them the created rewards and the equipment will get seperated, which you probably would not expect to happen. Due to my lack of Andriodskills i dont know how to fix this. Something like horizontal lines like in the webapp.

**Comment by saraolson** [comment]
We have changed the rewards column to separate custom rewards from gear/item rewards now, so reordering the custom rewards may be more do-able now?
