### ISSUE TITLE
In guild chat messages, chat messages older are not available.

### ISSUE THREAD

**Issue by anrehman** [HabitRPG/habitica-android#640]
Hello,

I am new to Habitica, and will be happy to contribute to this project in any way possible. In android application, chat messages for guild are shown only till 4 days and earlier messages are not visible. I missed reply to my message that was like 1 week ago and wasn't able to get to it. 

It will be very helpful if search or pagination could be enabled in chat messages later in time.

Thank you.

**Comment by Alys** [comment]
@anrehman already know this, I'm copying shanaqui's reply from the Report a Bug guild for reference for anyone else wondering about this:

**@anrehman Each chat only holds 200 messages -- it's based on the number of messages, not time.**

Since this is a deliberate feature, I'm closing this issue.

@anrehman When you find something you think is a bug, you're welcome to report it,  but it's best to do that in just one place to avoid double handling. The Report a Bug guild is generally the best place and if it's necessary for it to be reported elsewhere, an admin will advise you about that. :)

If you're interested in contributing to Habitica, we'd love your help! Have a look at [Contributing to Habitica](http://habitica.wikia.com/wiki/Contributing_to_Habitica) on the wiki for information about all the ways, and the relevant guilds.
