### ISSUE TITLE
No way to review Community Guidelines if you've already agreed to them

### ISSUE THREAD

**Issue by SabreCat** [HabitRPG/habitica-android#649]
If a user has accepted the Community Guidelines, there's no way within the app to return to and review them, unless a direct link is provided somewhere in chat. It'd make sense to have a way of bringing the Guidelines screen back up via "Help & FAQ" or "About", or even somewhere on the social screens.

**Comment by AlbRoehm** [comment]
The easiest way would be to set up a new pair of question & answer in the database, to make them appear at the end of the list, or suitable position.

**Comment by saraolson** [comment]
This will be added once we do the tavern design update in 1.5

**Comment by saraolson** [comment]
technically there is now a way to review the community guidelines at any time from the tavern, they just aren't mobile-screen friendly. tapping the button opens the guidelines in a browser and you have to scroll right and left as text is displayed off screen. 

since the fix for that would be making the community guidelines webpage more mobile-friendly rather than a fix in the app, i'm going to close this. feel free to reopen if we want a different solution within the app!
