### ISSUE TITLE
Why seeds make as a module

### ISSUE THREAD

**Issue by d954mas** [HabitRPG/habitica-android#677]
Why seeds make as a module, when it can be a dependency?
repositories {
   maven {
       url  "https://dl.bintray.com/seedsinc/maven"
   }
}
dependencies {
   compile('com.playseeds:android-sdk:0.4.1')
}

**Comment by vIiRuS** [comment]
Because it contains the [IInAppBillingService.aidl](https://github.com/therealseeds/seeds-sdk-android/blob/master/sdk/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl), that is also included by the [android checkout](https://github.com/serso/android-checkout/blob/master/lib/src/main/aidl/com/android/vending/billing/IInAppBillingService.aidl) library, that we use. So it doesn't compile, because that file ends up existing twice. In the module I added, I removed the file manually to make it work. If there is a different way to solve this, that lets us add it as a dependency, I'm open to change it.

**Comment by d954mas** [comment]
I understand the problem. I don't know the better solution.
