### ISSUE TITLE
Make Website and app to use different audio sound themes

### ISSUE THREAD

**Issue by AlbRoehm** [HabitRPG/habitica-android#685]

**Comment by AlbRoehm** [comment]
I'm not really sure anymore if this is an issue. Anyway .. i thought it would be nice to have a button to switch of the sound in the app without changing the audiotheme (which will also change the theme on the website). Most of the time i would not want the app to play sound, when I'm not at home so i would switch them of in the app, but i like to have them on the website...

**Comment by GuyKroizman** [comment]
I think we should view the app and web app as two separate application. (And Indeed they are)
Consider we link the application sound now; it is very conceivable that after that someone will open an issue to be able to have the app unmuted but the web app muted.
You should be able to silence you phone app without removing the sound theme.
You should be able to do it by lowering the audio level of "Music".
Currently due to a bug (none opened) you need to silence the audio level of "Notifications".
For that there is a open [PR](https://github.com/HabitRPG/habitica-android/pull/738)

**Comment by phillipthelen** [comment]
After some discussion we decided that this is not something we will pursue. Sorry for that.
