### ISSUE TITLE
Creating a Aspiring Blacksmith Andriod App Guild

### ISSUE THREAD

**Issue by AlbRoehm** [HabitRPG/habitica-android#697]
Do you guys see a chance to create a "Aspiring Blacksmith" sub guild for the Android app? Sometimes i would like to discuss or ask something, but most of the time i think its the wrong place to ask ... 

Anybody else also got this feeling?

**Comment by Alys** [comment]
You can use the current Aspiring Blacksmiths guild for Android (and iOS) questions if you want to. Other Android coders have in the past and it's certainly permitted.

My personal feeling is that it would be better to not start a new one because it will be another location for admins and coders to monitor, although if other admins feel differently, that's fine with me.

Some information is equally relevant to Android and iOS and website coding, so having separate guilds means either double-posting, or having coders monitor both guilds to avoid missing useful information.

**Comment by AlbRoehm** [comment]
I get your point. If nobody else responds we can probably skip this and leave everything like it was before...
