### ISSUE TITLE
API Tests fail

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-android#757]
For some reason the API tests fail because testsubscriber assertion that the network request was completed is not true. This only happens when running the tests through travis or the command line (using the same command as on travis). Running them through android studio works.

**Comment by caipivara** [comment]
@vIiRuS  what do you mean by API tests? how can I run them from the console/android studio?

**Comment by vIiRuS** [comment]
This refers to these tests: https://github.com/HabitRPG/habitica-android/tree/develop/Habitica/src/test/java/com/habitrpg/android/habitica/api
You can run them by uncommenting them and then using the run button in the file in AS.

**Comment by aleien** [comment]
Hello!
I wanted to give this one a shot, but ended up with trouble: NPE while initializing test runner. Have you experienced that?
`java.lang.RuntimeException: java.lang.NullPointerException

	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:155)
	at org.robolectric.res.ResourceTableFactory.newResourceTable(ResourceTableFactory.java:43)
...`
I tried to run tests with set "Working directory" as $MODULE_DIR$, but it didn't help. Do you run specific configuration for tests?
Also Travis CI seems to fail due to shortage of android sdk license acceptance ):

Could you please, point me out, how to set local machine server for tests? I suppose even if I manage to win battle against robolectric, it'll throw exception due to production server in settings (: Do I need only to uncomment strings with local emulator address and port? Seems like magic)

**Comment by beffymaroo** [comment]
@aleien It's been a while- are you still interested in working on this, or actively working on it? Let us know! Thank you.

**Comment by aleien** [comment]
Hi!
No, since I got no answer I abandoned this problem

**Comment by beffymaroo** [comment]
@aleien Thanks for letting us know. I'm changing the status back to Help Wanted.
