### ISSUE TITLE
Task attributes are displayed even if the point allocation method is not "Distribute points based on task activity"

### ISSUE THREAD

**Issue by MegaDerf** [HabitRPG/habitica-android#784]
When creating or editing a task in the Android app, you can always give to it one of four different attributes: "Physical", "Mental", "Social" or "Other". These attributes are used only if "Automatic allocation" is ON and set to "Distribute points based on task activity".

In the website, these attributes are shown only if this option is selected, while in the Android app they are always there, even if the current allocation method makes them useless.

**Comment by Alys** [comment]
Based on some testing, this might be because the app's code is checking for `preferences.allocationMode` being `taskbased` but isn't also checking the value of `preferences.automaticAllocation`.

The attribute options in the task edit screen should be shown only if `preferences.allocationMode` is `taskbased` and `preferences.automaticAllocation` is `true`.
