### ISSUE TITLE
Removing like from messages removes it from all messages

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-android#817]
This seems to only affect the display. The messages aren't actually all unliked. But the app updates the display to display it incorrectly.

**Comment by GautamMandsorwale** [comment]
Hey, @vIiRuS 

Can you please provide more info on what exact help do you need for this issue?

**Comment by vIiRuS** [comment]
We marked issues like this because of the hacktoberfest. So the help wanted would basically be a fix for the issue :)

let me know if you'd like to tackle this one and/or if you have any questions!

**Comment by camendoza94** [comment]
Hi @vIiRuS . I haven't been able to build the project in Android Studio. 
`Execution failed for task ':Habitica:processAmazonDebugGoogleServices'.
No matching client found for package name 'com.habitrpg.android.habitica.debug'`
I think the problem is the google-services.json. Does it need a special configuration on Firebase? Thanks.

**Comment by vIiRuS** [comment]
There is an example file for that file in the Habitica folder. If you
create a copy of that and rename it to google-services.json, it should work.
Also, make sure you are using android studio 3.0

-- 
Phillip Thelen
Sent with Airmail

**Comment by camendoza94** [comment]
I think that problem is fixed but now it is throwing an error that it can't find a STAGING_KEY variable on the ApiClientImpl class. What could that be?
