### ISSUE TITLE
Misleading message when deleting an account

### ISSUE THREAD

**Issue by sarna** [HabitRPG/habitica-android#882]
When deleting an account, user gets a message that reads: "Are you sure? This will delete your account forever, and it can never be restored! You will need to register a new account to use Habitica again. Banked or spent Gems will not be refunded. If you\'re absolutely certain, type your password into the text box below."
User shouldn't type their password there - they should type "DELETE". Typing the password doesn't work, and the box isn't suitable for typing in passwords - it's a normal text box, the password is visible and stored in phone's dictionary.

**Comment by Alys** [comment]
As @vIiRuS mentions at https://github.com/HabitRPG/habitica-android/pull/883#issuecomment-344704763 , what the user types depends on whether their account uses local or social media authentication. In addition, if the user's account has both methods of authentication, they must type their password. The api code that processes what they type is at https://github.com/HabitRPG/habitica/blob/67564317fbf9aea308254374577f58604c770206/website/server/controllers/api-v3/user.js#L394

**Comment by sarna** [comment]
I'm afraid my scarce JS knowledge won't be enough to fix this issue, unfortunately.

**Comment by ajsviado** [comment]
Submittted a pull request

**Comment by saraolson** [comment]
@ajsviado thank you! we're working on an iOS release right now but we'll review it and release with the next android update asap.

**Comment by Alys** [comment]
I'm reopening this because the bug is back: When you log in to the Android app using an account that has social media authentication and no password, if you try to delete the account, the instructions you see tell you to enter your password.

The instructions should tell you to enter "DELETE" using the `deleteSocialAccountText` string:
https://github.com/HabitRPG/habitica/blob/0379f341b9c9959f9e40a1379e3b167be4e0cfcb/website/common/locales/en/settings.json#L68

**Comment by Alys** [comment]
That was tested in app version 1.9.1 (2135)
