### ISSUE TITLE
0 gems appears in all player's profiles

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#911]
When you view the profile for yourself or other players, it contains a gem count, but the count is always 0.

The number of gems for players other than yourself should never be shown for privacy reasons, so it's correct that the actual count isn't shown, but it's misleading that the count is displayed as zero.

There's no privacy problem with displaying your own gem count in your own profile of course, but I suggest for consistency that the gem count isn't shown there either.

**Comment by kent12t** [comment]
To add on, opening your own account like opening other people's account, ie. from your name on chats or the Party page, the gems will still be 0 too (I have a few and can see it on task page, but not when I open it this way). The same goes for hourglasses, it doesn't appear, but the app tries to load it and since it has a zero value (just like the gems) it is not displayed (I'm aware that 0 hourglass is not displayed).

content://media/external/file/144541

**Comment by kemirea** [comment]
What is the intended UI here with regards to currencies and viewing other users' profiles? It would make sense to me to not show any currency at all, but I'm a fairly new Habitica user so perhaps I haven't discovered the use for seeing the amount of gold other users have.

**Comment by Alys** [comment]
Your Gems should always be hidden from other players because they're related to your real-world finances.

Traditionally we've had no objections to Gold being visible to anyone. It can be thought of as a measure of progress in tasks, just like XP is, and so can be of interest to see how a friend or party mate is doing, although there's so many factors that affect it (and XP) that the number isn't always meaningful (Rewards, equipment, quests, tasks, Fix Character Values). Seeing another player's Gold (and XP and other stats) can let you help the player with problems they're having (for example, "Why can't I buy the contributor sword?" -- "You don't have enough gold. If you're seeing that you have more than 123 GP, your app/website is showing old data and you need to sync"). The ability to help players like that is probably the biggest factor in deciding whether to show it. I don't see any privacy issues with showing it. Some players like talking about their Gold as a measure of their progress so they'd be in favour of showing it.

**Comment by kent12t** [comment]
@kemirea The expected behaviour is that it shouldn't show other people's gem and hourglass -- and the app shows it as 0  but why show something that doesn't need to be showed?? I don't think it has any use to see other people's gold stash, and if removing it is necessary to remove the 0 counter for both gems and hourglass it should be fine (as I said it has limited use to *other* user). I can't speak for the mods or staff but that's my take on this situation/issue. :)

**Comment by Alys** [comment]
Ah yes, Hourglasses too should not be shown to other players. Thanks @kent12t - I'd forgotten they can be considered as currency.

There are uses for showing Gold. The code to display Gems and Hourglasses should be separate from the code for displaying Gold.

**Comment by kemirea** [comment]
Thanks for the clarifications! I'm still familiarizing myself with the codebase, but it shouldn't be difficult to hide Gems and Hourglasses, or currencies altogether. I was just curious since, from a personal user perspective, I didn't see any significant benefit to other users' Gold being visible. The UI also looked cleaner to me if all currencies were hidden when viewing full profiles.

Is it alright if I take on this issue?
