### ISSUE TITLE
Beast Master count of "0" is displayed (probably also for Mount Master and Triad Bingo)

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#921]
When you have received the Beast Master achievement but have not yet released your pets, a "0" displays on the Beast Master badge. This is confusing to players who don't yet know that the count increments each time you release your pets. The preferred display is showing the number only when it's 1 or greater.

The same thing applies to the Mount Master and Triad Bingo achievements if they are also displaying a 0 before you've released your mounts / pets+mounts.

Here's an example showing a zero count for Mount Master:
![screenshot_2018-01-14_11-55-49](https://user-images.githubusercontent.com/1495809/34912052-f3b8573e-f921-11e7-998a-61d6981ca3e7.png)

Some technical information for the coder who works on this:

When you've obtained the Beast Master achievement, this field in the user's document is `true`: `achievements.beastMaster`

Similarlly for Mount Master and Triad Bingo: `achievements.mountMaster` and `achievements.triadBingo`

When you've released your pets once, `achievements.beastMasterCount` is set to `1` (an integer)
When you've released your mounts once, `achievements.mountMasterCount` is set to `1`
When you've released both pets and mounts together, `achievements.triadBingoCount` is set to `1`

**Comment by saraolson** [comment]
@Alys i'm a little confused on how/why this works the way it's supposed to. you get the beast/mount master achievement for collecting all 90 original pets/mounts, that part makes sense, but then why does the count go up to 1 only after you release? 

also, should we only show a count when its 2+, since having the achievement in the first place should imply its at 1?

**Comment by Alys** [comment]
The number shows the number of times you have released your Pets. There's no count of the number of times you have collected them all (i.e. you get the Beast Master achievement once only). If you hover over the achievement in the website you see text that explains the number (assuming you've released your Pets at least once). If you want consistency with the website, then the app won't display 0 but will display 1 and greater.

**Comment by saraolson** [comment]
okay so the count actually isnt related to the achievement at all, which is why the 0 shows when you get the achievement. id be okay with making this sync up with web atm but this pattern doesn't make a lot of sense to me overall. if we have a count on an achievement, it should be counting how many times you got that achievement, not something unrelated?

**Comment by Alys** [comment]
It's related to the achievement in that you can't release pets (or mounts) until you have the Beast Master (or Mount Master) achievement, but I have no objections to it being changed if it's done in a way that doesn't make it a breaking change for the API. That's more of a general Habitica question though. For this issue with the current achievement behaviour, the only change needed is for the number to not be shown when it's zero.
