### ISSUE TITLE
In daily notification allow to check off the daily

### ISSUE THREAD

**Issue by droundy** [HabitRPG/habitica-android#962]
Checking off a daily should be possible directly from a notification, without opening habitica, which would be far more convenient.

**Comment by amohnacs15** [comment]
I'd like to look into this one. expect questions to follow

**Comment by amohnacs15** [comment]
So I'm ready to get started on the enhancement.  A few questions on the UX though : 

- Currently we are getting all of our tasks of type DAILY from our TaskManager and if any of them are due we display the notification. **How many Dailies do we want to the user to see when the notification is tripped and how?** Each notification could have it's own notification that would have a single checkbox (the way email does it for multiple mailboxes) or we could do our own version of an expandable notification where all the dailies and their checkboxes would be displayed in list form.

- **What is the experience for checking these boxes?** As they check a box does the notification disappear or do they check the dailies they want to complete and then click a SUBMIT button?

Thanks for taking the time.

**Comment by phillipthelen** [comment]
Hey,

Correct me if I'm wrong, but I think we are referring to two different things. The notifications the issue refers to are the reminders for individual dailies that you can configure when editing a daily. They then pop up at the specified time for each daily. It sounds like you are referring to the daily notification you can configure in the apps settings? The settigns one shouldn't have any actions to check off tasks (since as you probably already saw it wouldn't be possible to get a good UX) but instead the individual task reminders should have this feature. I'd imagine them being added through [Notification actions](https://developer.android.com/guide/topics/ui/notifiers/notifications#Actions), so that the notification has a "Complete task" action.

I don't mind you converting NotificationPublisher! I've also used the automatic Android studio migration tool in the past very successfully with cleanup afterwards to make some things nicer.
